export const STRIPE_PAYMENT_FAIL    = 'STRIPE_PAYMENT_FAIL';
export const FETCH_SURVEYS          = 'FETCH_SURVEYS';
export const FETCH_SURVEY           = 'FETCH_SURVEY';

export const DELETE_SURVEY_SUCCESS  = 'DELETE_SURVEY_SUCCESS';
export const DELETE_SURVEY_FAIL     = 'DELETE_SURVEY_FAIL';

export const FETCH_USER             = 'FETCH_USER';
export const USER_SKIP_CREDITS      = 'USER_SKIP_CREDITS';

export const TOGGLE_BACKDROP        = 'TOGGLE_BACKDROP';
export const TOGGLE_SIDEBAR         = 'TOGGLE_SIDEBAR';


export const INPUT_CHANGE_POST_TITLE = 'INPUT_CHANGE_POST_TITLE';
export const INPUT_CHANGE_POST_CONTENT = 'INPUT_CHANGE_POST_CONTENT'
export const FETCH_POSTS = 'FETCH_POSTS';
export const SUBMIT_POST_SUCCESS = 'SUBMIT_POST_SUCCESS';
export const SUBMIT_POST_FAIL = 'SUBMIT_POST_FAIL';
